import React from 'react'
import Modal from 'react-modal';
import { FaTimes } from 'react-icons/fa';
import DataDisplayModal from '@/components/FacultyDashboard/Profile/components/Common/FeildsData';
import ImageDisplay from '@/components/FacultyDashboard/Profile/components/Common/Imagedisplay';

const RevenueByHEIDataDisplay = ({ isOpen, closeModal, data }) => {
  const formattedDataStage1 = [
    { label: 'Title of Invention', value: data.Title_of_Invention },
    { label: 'Name of Lead Inventor', value: data.Name_of_Lead_Inventor },
    { label: 'Designation of Lead Inventor', value: data.Designation_of_Lead_Inventor },
    { label: 'Department of Lead Inventor', value: data.Department_of_Lead_Inventor },
  ];
  const formattedDataStage2 = [
    { label: 'Nationality', value: data.Nationality },
    { label: 'Date of Agreement', value: data.Date_of_Agreement.split("T")[0] },
    { label: 'Start Date', value: data.StartDate.split("T")[0] },
    { label: 'End Date', value: data.EndDate.split("T")[0] },
  ];
  const formattedDataStage3 = [
    { label: 'Licensee Name', value: data.Licensee_Name },
    { label: 'Licensee Organization', value: data.Licensee_Organization },
    { label: 'Fee / Royalty Share Percentages', value: data.Fee_Royalty_Share_Percentages },
    { label: 'Total Amount', value: data.Total_Amount },
    { label: 'ORIC Approved Share', value: data.ORIC_Approved_Share },
    { label: 'ORIC Received Share', value: data.ORIC_Received_Share },
  ];
  const imageData = [
    {
      label: 'Audited Statement',
      value: `/uploadFile/${data.username}/RevenueByHEI/${data.Title_of_Invention}_AuditedStatement.png`
    },
  ];
  const formattedDataStage4 = [
    ...(data.Remarks ? [{ label: 'Remarks', value: data.Remarks }] : []),
  ];

  return (
    <Modal
      isOpen={isOpen}
      onRequestClose={closeModal}
      contentLabel="Revenue Generated by HEI Data"
      className="flex gap-y-8 flex-col bg-white w-full h-screen shadow-lg ml-auto overflow-y-auto mr-auto rounded-md border-4 p-10"
    >
      <div className='flex flex-col pl-10'>
        <div className="flex justify-end items-end  gap-x-6">
          <FaTimes className="text-red-500 text-xl cursor-pointer mt-8" onClick={closeModal} />
        </div>
        <DataDisplayModal
          title="Invention Details"
          gridClassName="grid-cols-2"
          data={formattedDataStage1}
        />
        <DataDisplayModal
          title="Agreement Details"
          gridClassName="grid-cols-2"
          data={formattedDataStage2}
        />
        <DataDisplayModal
          title="Licensee Details"
          gridClassName="grid-cols-2"
          data={formattedDataStage3}
        />
        <DataDisplayModal
          title="Additional Details"
          data={formattedDataStage4}
        />
        <ImageDisplay title="Audited Statement" data={imageData} />
      </div>
    </Modal>
  );
}

export default RevenueByHEIDataDisplay;
