import React from 'react';
import Modal from 'react-modal';
import { FaTimes } from 'react-icons/fa';
import DataDisplayModal from '@/components/FacultyDashboard/Profile/components/Common/FeildsData';
import ImageDisplay from '@/components/FacultyDashboard/Profile/components/Common/Imagedisplay';

const RevenueByORICDataDisplay = ({ isOpen, closeModal, data }) => {
  const formattedDataStage1 = [
    { label: 'Name of Research Grant', value: data.Name_of_Research_Grant },
    { label: 'Nationality', value: data.Nationality },
    { label: 'Title of Research Proposal', value: data.Title_of_ResearchProposal },
    { label: 'Name of PI', value: data.Name_of_PI },
    { label: 'Designation of PI', value: data.Designation_of_Pi },
    { label: 'Department of PI', value: data.Department_of_Pi },
  ];

  const formattedDataStage2 = [
    { label: 'Start Date', value: data.StartDate.split("T")[0] },
    { label: 'End Date', value: data.EndDate.split("T")[0] },
    { label: 'Total Funding Approved', value: data.Total_Funding_Approved },
    { label: 'Total Funding Released', value: data.Total_Funding_Released },
    { label: 'ORIC Overhead in Approved Funding', value: data.ORIC_Overhead_in_Approved_Funding },
    { label: 'ORIC Overhead in Released Funding', value: data.ORIC_Overhead_in_Released_Funding },
  ];
  const imageData = [
    {
      label: 'Audited Statement',
      value: `/uploadFile/${data.username}/RevenueByORIC/${data.Title_of_ResearchProposal}_AuditedStatement.png`
    },
  ];
  const formattedDataStage3 = [
    ...(data.Collaborating_Partner ? [{ label: 'Collaborating Partner', value: data.Collaborating_Partner }] : []),
    ...(data.Remarks ? [{ label: 'Remarks', value: data.Remarks }] : []),
  ];


  return (
    <Modal
      isOpen={isOpen}
      onRequestClose={closeModal}
      contentLabel="Revenue Generated by ORIC Data"
      className="flex gap-y-8 flex-col bg-white w-full h-screen shadow-lg ml-auto overflow-y-auto mr-auto rounded-md border-4 p-10"
    >
      <div className='flex flex-col pl-10'>
        <div className="flex justify-end items-end gap-x-6">
          <FaTimes className="text-red-500 text-xl cursor-pointer mt-8" onClick={closeModal} />
        </div>
        <DataDisplayModal
          title="Research Grant Details"
          gridClassName="grid-cols-2"
          data={formattedDataStage1}
        />
        <DataDisplayModal
          title="Duration and Funding Details"
          gridClassName="grid-cols-2"
          data={formattedDataStage2}
        />
        <DataDisplayModal
          title="Additional Details"
          data={formattedDataStage3}
        />
        
         <ImageDisplay title="Audited Statement" data={imageData} />
      </div>
    </Modal>
  );
}

export default RevenueByORICDataDisplay;
