import React, { useState } from "react";
import RevenueByORIC from "./components/RevenueByORIC";
import RevenueByHEI from "./components/RevenueByHEI";
import Trainings_Events from "./components/Trainings_Events";
import { Visits } from "./components/Visits";

export default function SustainabilityTabs() {
  const [selectionTab, setSelectionTab] = useState("");
  const [showModal, setShowModal] = useState(true); 
  const [isIPMode, setIsIPMode] = useState(false); 
  const tabs = [
    {
      name: "Revenue Generated By ORIC",
      component: <RevenueByORIC />,
    },
    {
      name: "Revenue Generated by HEI",
      component: <RevenueByHEI />,
    },
    {
      name: "Events/Trainings",
      component: <Trainings_Events />,
    },
    
    {
      name: "Number of Visits",
      component: <Visits />,
    },
  ];

  const [activeTab, setActiveTab] = useState("Revenue Generated By ORIC");

  const handleTabChange = (tab) => {
    setActiveTab(tab.name);
  };

  return (
    <>
      <div className="flex justify-end"></div>

      <div className="flex  text-base font-semibold  gap-y-10  px-4 pb-10 pt-5 rounded-[10px] w-full my-10">
        <div className="flex flex-col items-start  justify-start gap-y-6 pl-6">
          {tabs.map((tab, index) => (
            <div
              key={index}
              onClick={() => handleTabChange(tab)}
              className={`${
                activeTab === tab.name
                  ? "text-white bg-blue-900"
                  : "bg-white text-blue-900"
              } cursor-pointer rounded-full tab-shadow font-bold text-base leading-[22px] px-4 py-1`}>
              {tab.name}
            </div>
          ))}
        </div>
        <div className="w-full">
          {tabs.map((tab, index) => (
            <div key={index}>
              {activeTab === tab.name && tab.component}
            </div>
          ))}
        </div>
      </div>
    </>
  );
}
