import React, { useState } from "react";
import RevenueByORIC from "./components/RevenueByORIC";
import RevenueByHEI from "./components/RevenueByHEI";
import Trainings_Events from "./components/Trainings_Events";
import { Visits } from "./components/Visits";

export default function SustainabilityTabs() {
  const [selectionTab, setSelectionTab] = useState("");
  const [showModal, setShowModal] = useState(true); // Default true, adjust based on your use case
  const [isIPMode, setIsIPMode] = useState(false); // State to manage IP mode
  const tabs = [
    {
      name: "Revenue Generated By ORIC",
      component: <RevenueByORIC />,
    },
    {
      name: "Revenue Generated by HEI",
      component: <RevenueByHEI />,
    },
    {
      name: "Events/Trainings",
      component: <Trainings_Events />,
    },
    
    {
      name: "Number of Visits",
      component: <Visits />,
    },
  ];

  const [activeTab, setActiveTab] = useState("Revenue Generated By ORIC");

  const handleTabChange = (tab) => {
    setActiveTab(tab.name);
  };

  return (
    <>
      <div className="flex justify-end"></div>

      <div className="flex flex-col items-center text-base font-semibold  gap-y-10 research-shadow px-4 pb-10 pt-5 rounded-[10px] bg-white w-full my-10">
        <div className="flex items-start justify-start p-4 gap-x-28 text-sm">
          {tabs.map((tab, index) => (
            <div
              key={index}
              onClick={() => handleTabChange(tab)}
              className={`${
                activeTab === tab.name
                  ? "border-blue-900 text-white p-4 border-b-[3px]"
                  : "border-2 bg-white border-blue-950 text-black "
              } flex items-center border-2 bg-blue-950 p-4 rounded-md text-black justify-center h-12 cursor-pointer `}
            >
              {tab.name}
            </div>
          ))}
        </div>
        <div className="w-full">
          {tabs.map((tab, index) => (
            <div key={index}>
              {activeTab === tab.name && tab.component}
            </div>
          ))}
        </div>
      </div>
    </>
  );
}
